### ISSUE TITLE
what processor is in your x270?

### ISSUE THREAD

**Issue by rat1bor** [HieuPBT/Lenovo_ThinkPad_X270_Hackintosh_Ventura#1]
Hello! I wanted to install a hackintosh for my x270. I have an i5 7200U processor, can you tell me what your pc parameters are?

**Comment by HieuPBT** [comment]
Sr mate, the EFI is still in patching process. It will be completed soon.

Btw, my processor I5 6300U

**Comment by rat1bor** [comment]
thanks for the info
